'use client'
import {useEffect,useMemo,useState} from 'react'
import {Gamepad2,Trophy,UserRound,Users,ShoppingBag,WalletCards,LogOut,X,Sparkles,Shield,Send,Volume2,VolumeX,Settings,Coins,MessageCircle,Flag,UserX} from 'lucide-react'
import {moderateVietnamese} from '../lib/moderation'

const games=[['🌴','Nha Trang Life','Roleplay','Khám phá thành phố biển, làm nhiệm vụ và giao lưu.'],['⚔️','Viet Battle','PvP','Đấu trường FFA, kỹ năng, XP và bảng xếp hạng.'],['🌾','Nông Trại Việt','Simulation','Trồng trọt, nâng cấp đảo và giao dịch vật phẩm.'],['🏙️','Phố Việt RP','Roleplay','Xây nhân vật, nghề nghiệp và thành phố của riêng bạn.'],['🚗','Đường Phố VN','Racing','Đua xe, drift và mở khóa phương tiện.'],['🧟','Zombie Việt Nam','Survival','Sinh tồn theo wave, boss và loot.']]
type User={id:string;username:string;email:string;coins:number;xp:number;level:number;avatar:string;email_verified:boolean}
type Chat={id:number,user:string,text:string,time:string,flagged?:boolean}
function GoogleIcon(){return <svg width="20" height="20" viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285F4" d="M21.35 12.23c0-.72-.06-1.41-.18-2.07H12v3.92h5.24a4.48 4.48 0 0 1-1.94 2.94v2.45h3.14c1.84-1.7 2.91-4.2 2.91-7.24Z"/><path fill="#34A853" d="M12 21.75c2.63 0 4.84-.87 6.45-2.36l-3.14-2.45c-.87.58-1.98.93-3.31.93-2.54 0-4.69-1.72-5.46-4.03H3.3v2.53A9.74 9.74 0 0 0 12 21.75Z"/><path fill="#FBBC05" d="M6.54 13.84A5.85 5.85 0 0 1 6.23 12c0-.64.11-1.26.31-1.84V7.63H3.3A9.75 9.75 0 0 0 2.25 12c0 1.57.38 3.05 1.05 4.37l3.24-2.53Z"/><path fill="#EA4335" d="M12 6.13c1.43 0 2.71.49 3.72 1.45l2.79-2.79C16.84 3.16 14.63 2.25 12 2.25a9.74 9.74 0 0 0-8.7 5.38l3.24 2.53C7.31 7.85 9.46 6.13 12 6.13Z"/></svg>}
function DiscordIcon(){return <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M19.54 5.13A16.5 16.5 0 0 0 15.48 3.9l-.5 1.02a15.1 15.1 0 0 0-5.96 0l-.5-1.02a16.5 16.5 0 0 0-4.06 1.23C1.89 9.02 1.2 12.8 1.55 16.53a16.7 16.7 0 0 0 4.99 2.51l1.21-1.65c-.66-.25-1.29-.56-1.88-.92l.46-.35c3.63 1.7 7.57 1.7 11.16 0l.47.35c-.6.36-1.22.67-1.89.92l1.21 1.65a16.7 16.7 0 0 0 4.99-2.51c.41-4.33-.7-8.08-2.73-11.4ZM8.58 14.35c-1.08 0-1.97-.99-1.97-2.2s.87-2.2 1.97-2.2 1.98.99 1.97 2.2c0 1.21-.87 2.2-1.97 2.2Zm6.84 0c-1.08 0-1.97-.99-1.97-2.2-1.08 0-1.97-.99-1.97-2.2s.87-2.2 1.97-2.2 1.98.99 1.97 2.2c0 1.21-.87 2.2-1.97 2.2Z"/></svg>}

export default function Home(){
 const[user,setUser]=useState<User|null>(null),[show,setShow]=useState(false),[admin,setAdmin]=useState(false),[mode,setMode]=useState<'login'|'signup'>('login'),[email,setEmail]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[chat,setChat]=useState<Chat[]>([]),[message,setMessage]=useState(''),[sound,setSound]=useState(true),[announcement,setAnnouncement]=useState(''),[announceTime,setAnnounceTime]=useState('10')
 const[players,setPlayers]=useState(128),[selectedGame,setSelectedGame]=useState('')
 const isAdmin=Boolean(user)
 useEffect(()=>{fetch('/api/auth/me').then(r=>r.json()).then(d=>d.user&&setUser(d.user));setChat([{id:1,user:'VietVerse',text:'Chào mừng đến kênh chat cộng đồng 🇻🇳',time:'now'},{id:2,user:'ModBot',text:'Hãy giữ cuộc trò chuyện văn minh. Từ ngữ tục tĩu sẽ được tự động che.',time:'now'}]);const q=new URLSearchParams(location.search);if(q.get('email')==='verified')setNotice('🎉 Email đã được xác minh!');if(q.get('oauth')==='error')setError('Đăng nhập OAuth thất bại. Hãy kiểm tra cấu hình Google/Discord trong Supabase.')},[])
 const online=useMemo(()=>players+Math.floor(Math.random()*7),[players])
 const submit=async()=>{setError('');setBusy(true);try{const path=mode==='login'?'/api/auth/login':'/api/auth/register';const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,username,password})});const d=await r.json();if(!r.ok)throw Error(d.error);if(mode==='signup'){setNotice('📩 Đã gửi link xác minh tới email.');setMode('login')}else{setUser(d.user);setShow(false);setNotice(`👋 Chào mừng ${d.user.username}!`)}}catch(e){setError(e instanceof Error?e.message:'Có lỗi xảy ra.')}finally{setBusy(false)}}
 const logout=async()=>{await fetch('/api/auth/logout',{method:'POST'});setUser(null);setShow(false);setAdmin(false);setNotice('Đã đăng xuất.')}
 const sendChat=()=>{if(!message.trim())return;const m=moderateVietnamese(message.trim());if(m.blocked)setNotice('🛡️ Tin nhắn có từ ngữ không phù hợp và đã được che.');setChat(c=>[...c,{id:Date.now(),user:user?.username||'Khách',text:m.text,time:'now',flagged:m.blocked}]);setMessage('')}
 const publishAnnouncement=()=>{if(!announcement.trim())return;setNotice(`📢 ${announcement} · hiển thị ${announceTime}s`);setAnnouncement('');setAdmin(false)}
 return <main className="vv">
  <nav className="nav"><div className="brand">🇻🇳 <span>Viet</span>Verse</div><div className="navlinks"><button className="pill" onClick={()=>document.getElementById('games')?.scrollIntoView({behavior:'smooth'})}><Gamepad2 size={16}/> Game</button><button className="pill" onClick={()=>setNotice('🏆 BXH đang đồng bộ XP/Coins.') }><Trophy size={16}/> BXH</button><button className="pill" onClick={()=>document.getElementById('chat')?.scrollIntoView({behavior:'smooth'})}><MessageCircle size={16}/> Chat</button>{user&&isAdmin&&<button className="pill adminBtn" onClick={()=>setAdmin(true)}><Shield size={16}/> Admin</button>}{user?<button className="pill" onClick={()=>setShow(true)}><UserRound size={16}/>{user.username}</button>:<button className="pill" onClick={()=>{setMode('login');setShow(true)}}><UserRound size={16}/> Đăng nhập</button>}</div></nav>
  <section className="hero"><div><span className="tag"><Sparkles size={13}/> V3 MEGA UPDATE</span><h1>Một Việt Nam.<br/><span> Một thế giới.</span></h1><p>Game hub cộng đồng với PvP, roleplay, survival, chat an toàn, XP, Coin, inventory, bạn bè và quản trị.</p><div className="actions"><button className="btn primary" onClick={()=>document.getElementById('games')?.scrollIntoView({behavior:'smooth'})}>Chơi ngay</button><button className="btn" onClick={()=>{setMode('signup');setShow(true)}}>Tạo tài khoản</button></div><div className="live"><i/> {online} người đang online · 6 game</div></div><div className="heroCard"><Shield size={30}/><h2>VietVerse Safety</h2><p>Chat tự động phát hiện và che từ ngữ tục tĩu tiếng Việt, kể cả cách viết cách ký tự.</p><div className="notice">🛡️ Văn minh · Không spam · Không xúc phạm</div></div></section>
  <section className="section" id="games"><div className="sectionHead"><h2>🎮 Game Hub</h2><span className="muted">Chọn game để vào phòng</span></div><div className="games">{games.map(([e,n,t,d])=><button className={`game ${selectedGame===n?'selected':''}`} key={n} onClick={()=>{setSelectedGame(n);setNotice(`🚀 Đang chuẩn bị phòng ${n}...`)}}><span className="emoji">{e}</span><strong>{n}</strong><small>{d}</small><span className="tag">{t}</span><b className="play">PLAY →</b></button>)}</div></section>
  {selectedGame&&<section className="section"><div className="panel gameRoom"><div><span className="tag">ROOM READY</span><h2>{selectedGame}</h2><p>Phòng demo đã sẵn sàng. Khi backend game được kết nối, nút này sẽ mở server tương ứng.</p></div><button className="btn primary" onClick={()=>setNotice(`🎮 Đã vào ${selectedGame}!`)}>Vào phòng</button></div></section>}
  <section className="section" id="chat"><div className="sectionHead"><h2>💬 Community Chat</h2><button className="iconBtn" onClick={()=>setSound(!sound)}>{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button></div><div className="chat panel">{chat.map(m=><div className="chatRow" key={m.id}><div className="avatar">{m.user[0]?.toUpperCase()||'V'}</div><div className="chatBody"><b>{m.user}</b><small>{m.time}</small><p>{m.text}{m.flagged&&<span className="flag"> 🛡️</span>}</p></div></div>)}<div className="chatInput"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendChat()} placeholder={user?'Nhắn tin văn minh...':'Đăng nhập để chat'}/><button className="btn primary" disabled={!user} onClick={sendChat}><Send size={17}/></button></div></div></section>
  <section className="section"><h2>🧩 Hệ thống</h2><div className="games"><div className="game"><UserRound/><strong>Avatar & Profile</strong><small>Level, XP, avatar và hồ sơ người chơi.</small></div><div className="game"><ShoppingBag/><strong>Shop & Inventory</strong><small>Coin, vật phẩm, skin và bộ sưu tập.</small></div><div className="game"><WalletCards/><strong>XP & Coins</strong><small>Phần thưởng và tiến trình được giữ theo tài khoản.</small></div><div className="game"><Users/><strong>Bạn bè & Party</strong><small>Kết nối người chơi và tham gia phòng.</small></div></div></section>
  {notice&&<div className="section"><div className="notice">{notice}<button onClick={()=>setNotice('')} className="noticeClose"><X size={18}/></button></div></div>}
  {user&&<div className="verified">👤 {user.username} · Lv.{user.level} · <Coins size={14}/> {user.coins}</div>}
  <footer className="footer">VietVerse 🇻🇳 · V3 Mega Update · Chat Safety enabled</footer>

  {show&&<div className="overlay"><div className="login"><button className="close" onClick={()=>setShow(false)}><X/></button>{user?<><h2>👤 {user.username}</h2><p>{user.email}</p><div className="stats"><div className="stat"><small>Coins</small><br/><b>{user.coins}</b></div><div className="stat"><small>XP</small><br/><b>{user.xp}</b></div><div className="stat"><small>Level</small><br/><b>{user.level}</b></div></div><button className="btn full" onClick={logout}><LogOut size={16}/> Đăng xuất</button></>:<><h2>{mode==='login'?'🔐 Đăng nhập':'✨ Tạo tài khoản'}</h2><p>{mode==='login'?'Đăng nhập VietVerse.':'Nhập email thật. Bạn sẽ nhận link xác minh.'}</p>{mode==='signup'&&<input className="field" placeholder="Username" value={username} onChange={e=>setUsername(e.target.value)}/>}<input className="field" type="email" placeholder="you@gmail.com" value={email} onChange={e=>setEmail(e.target.value)}/><input className="field" type="password" placeholder="Mật khẩu (8+ ký tự)" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<div className="error">{error}</div>}<button className="btn primary full" disabled={busy} onClick={submit}>{busy?'Đang xử lý...':mode==='login'?'Đăng nhập':'Tạo tài khoản'}</button>{mode==='login'&&<div className="oauth"><button className="oauthBtn" onClick={()=>location.href='/api/auth/oauth/discord'}><DiscordIcon/><span>Đăng nhập với Discord</span></button><button className="oauthBtn" onClick={()=>location.href='/api/auth/oauth/google'}><GoogleIcon/><span>Đăng nhập với Google</span></button></div>}<button className="mini" onClick={()=>{setMode(mode==='login'?'signup':'login');setError('')}}>{mode==='login'?'Chưa có tài khoản? Đăng ký':'Đã có tài khoản? Đăng nhập'}</button></>}</div></div>}

  {admin&&<div className="overlay"><div className="adminPanel"><button className="close" onClick={()=>setAdmin(false)}><X/></button><div className="adminTitle"><div><span className="tag"><Shield size={13}/> OWNER CONTROL</span><h2>Admin Panel</h2><p>Điều khiển nội dung, chat và thông báo VietVerse.</p></div><Settings/></div><div className="adminGrid"><div className="adminCard"><Users/><b>Online</b><strong>{online}</strong><small>người chơi</small></div><div className="adminCard"><MessageCircle/><b>Chat</b><strong>{chat.length}</strong><small>tin nhắn</small></div><div className="adminCard"><Flag/><b>Moderation</b><strong>ON</strong><small>lọc tục tiếng Việt</small></div><div className="adminCard"><Gamepad2/><b>Games</b><strong>6</strong><small>game hub</small></div></div><div className="adminSection"><h3>📢 Thông báo toàn web</h3><input className="field" placeholder="Nội dung thông báo..." value={announcement} onChange={e=>setAnnouncement(e.target.value)}/><div className="adminRow"><select className="field" value={announceTime} onChange={e=>setAnnounceTime(e.target.value)}><option value="5">5 giây</option><option value="10">10 giây</option><option value="30">30 giây</option><option value="60">60 giây</option><option value="0">Không tự hết</option></select><button className="btn primary" onClick={publishAnnouncement}><Send size={16}/> Gửi thông báo</button></div></div><div className="adminSection"><h3>🛡️ Quản lý chat</h3><div className="adminActions"><button className="btn"><UserX size={16}/> Chế độ chậm</button><button className="btn"><Flag size={16}/> Xem báo cáo</button><button className="btn" onClick={()=>setChat([])}><TrashIcon/> Xóa chat demo</button></div><p className="muted">Bộ lọc hiện che từ tục tiếng Việt và các biến thể cách ký tự ở phía client. Quyền admin thật cần được khóa thêm ở server bằng session + ADMIN_EMAIL/role.</p></div></div></div>}
 </main>
}
function TrashIcon(){return <span>🗑️</span>}
