'use client'

import { useState } from 'react'
import { Bell, Gamepad2, Shield, Sparkles, Trophy, UserRound, WalletCards, Users, ShoppingBag, Settings, X, CheckCircle2 } from 'lucide-react'

const games = [
  ['🌴','Nha Trang Life','Roleplay','Khám phá thành phố biển, lái xe và giao lưu.'],
  ['⚔️','Viet Battle','PvP','Đấu trường free-for-all với kỹ năng và bảng xếp hạng.'],
  ['🌾','Nông Trại Việt','Simulation','Trồng trọt, nâng cấp đảo và giao dịch vật phẩm.'],
  ['🏙️','Phố Việt RP','Roleplay','Xây nhà, làm nghề và tạo câu chuyện của riêng bạn.'],
]

export default function Home(){
 const [showLogin,setShowLogin]=useState(false),[showOtp,setShowOtp]=useState(false),[email,setEmail]=useState(''),[otp,setOtp]=useState(''),[password,setPassword]=useState(''),[username,setUsername]=useState('')
 const [notice,setNotice]=useState(''),[coins,setCoins]=useState(1250),[liked,setLiked]=useState<string[]>([]),[tab,setTab]=useState('home'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[verified,setVerified]=useState(false),[admin,setAdmin]=useState(false)
 const flash=(s:string)=>{setError('');setNotice(s)}
 const startSignup=async()=>{
   if(!/^\S+@\S+\.\S+$/.test(email)){setError('Hãy nhập email hợp lệ.');return}
   if(!username.trim()){setError('Hãy nhập username.');return}
   if(password.length<8){setError('Mật khẩu cần ít nhất 8 ký tự.');return}
   setBusy(true);setError('')
   try{const r=await fetch('/api/auth/send-otp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Không thể gửi OTP');setShowOtp(true);flash(`Mã OTP đã được gửi tới ${email}.`)}catch(e){setError(e instanceof Error?e.message:'Không thể gửi OTP.')}finally{setBusy(false)}
 }
 const verify=async()=>{
   if(!/^\d{6}$/.test(otp)){setError('Nhập đủ 6 số.');return}setBusy(true);setError('')
   try{const r=await fetch('/api/auth/verify-otp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,otp})});const d=await r.json();if(!r.ok)throw new Error(d.error||'OTP không đúng');setVerified(true);setShowOtp(false);setShowLogin(false);flash('🎉 Email đã xác minh thành công!')}catch(e){setError(e instanceof Error?e.message:'OTP không đúng.')}finally{setBusy(false)}
 }
 return <main className="vv">
  <nav className="nav"><div className="brand">🇻🇳 <span>Viet</span>Verse</div><div className="navlinks"><button className="pill hideMob" onClick={()=>setTab('games')}><Gamepad2 size={16}/> Game</button><button className="pill hideMob" onClick={()=>setTab('ranking')}><Trophy size={16}/> BXH</button><button className="pill hideMob" onClick={()=>setTab('friends')}><Users size={16}/> Bạn bè</button><button className="pill" onClick={()=>setShowLogin(true)}><UserRound size={16}/> {verified?'Tài khoản':'Đăng nhập'}</button></div></nav>
  <section className="hero"><div><span className="tag"><Sparkles size={13}/> V2 BIG UPDATE</span><h1>Một Việt Nam.<br/><span style={{color:'#2878ff'}}>Một thế giới.</span></h1><p>VietVerse là trung tâm game online dành cho cộng đồng Việt — avatar, bạn bè, game, chat, XP, coin và sự kiện trong cùng một thế giới.</p><div className="actions"><button className="btn primary" onClick={()=>{setTab('games');document.getElementById('games')?.scrollIntoView({behavior:'smooth'})}}>Chơi ngay</button><button className="btn" onClick={()=>setShowLogin(true)}>Tạo tài khoản</button></div><div className="stats"><div className="stat"><small>Người chơi</small><br/><b>1,284</b></div><div className="stat"><small>Game</small><br/><b>4</b></div><div className="stat"><small>VietCoins</small><br/><b>{coins.toLocaleString()}</b></div></div></div><div className="heroCard"><Bell size={24}/><h2>Trung tâm thông báo</h2><p>Thông báo có thể được phát từ Admin và lưu để người chơi thấy lại khi đăng nhập.</p><div className="notice">✨ Chào mừng đến VietVerse V2!<br/><small>Auth OTP và hệ thống game đang được nâng cấp.</small></div></div></section>
  <section className="section" id="games"><h2>🎮 Khám phá game</h2><div className="games">{games.map(([e,n,t,d])=><button className="game" key={n} onClick={()=>{setLiked(v=>v.includes(n)?v.filter(x=>x!==n):[...v,n]);flash(`🚀 ${n} đã được chọn. Server matchmaking sẽ kết nối khi backend game được bật.`)}}><span className="emoji">{e}</span><strong>{n}</strong><small>{d}</small><br/><span className="tag">{t}</span></button>)}</div></section>
  <section className="section"><h2>🧩 Hệ thống VietVerse</h2><div className="games"><div className="game"><WalletCards/><strong>Wallet & Shop</strong><small>Coin, daily reward, shop và inventory.</small><button className="mini" onClick={()=>{setCoins(c=>c+100);flash('🪙 Daily reward +100 VietCoins!')}}>Nhận +100</button></div><div className="game"><UserRound/><strong>Avatar</strong><small>Tùy chỉnh nhân vật và lưu profile.</small><button className="mini" onClick={()=>flash('👤 Avatar Editor đang mở trong bản UI kế tiếp.')}>Mở Avatar</button></div><div className="game"><ShoppingBag/><strong>Shop</strong><small>Trang phục, hiệu ứng và vật phẩm.</small><button className="mini" onClick={()=>flash('🛍️ Shop đã sẵn sàng cho catalog backend.')}>Mở Shop</button></div><div className="game"><Trophy/><strong>XP & BXH</strong><small>Level, nhiệm vụ và leaderboard.</small><button className="mini" onClick={()=>setTab('ranking')}>Xem BXH</button></div></div></section>
  {tab==='ranking'&&<section className="section"><div className="panel"><h2>🏆 Bảng xếp hạng</h2><div className="rank"><b>🥇 1 · VietPro</b><span>Lv. 42 · 18,420 XP</span></div><div className="rank"><b>🥈 2 · NoobVN</b><span>Lv. 39 · 16,870 XP</span></div><div className="rank"><b>🥉 3 · DoraVN</b><span>Lv. 37 · 15,210 XP</span></div><div className="rank"><b>4 · LGK</b><span>Lv. 12 · 2,450 XP</span></div></div></section>}
  {tab==='friends'&&<section className="section"><div className="panel"><h2>👥 Bạn bè</h2><p>Danh sách bạn bè và party sẽ đồng bộ với tài khoản sau khi database được nối.</p><button className="btn primary" onClick={()=>flash('👥 Party system foundation đã sẵn sàng.')}>Tạo Party</button></div></section>}
  {notice&&<div className="section"><div className="notice">{notice}<button style={{float:'right',background:'transparent',color:'#fff',border:0,fontSize:20}} onClick={()=>setNotice('')}>×</button></div></div>}
  {verified&&<div className="verified"><CheckCircle2 size={18}/> Email đã xác minh</div>}
  <footer className="footer">VietVerse 🇻🇳 · V2 Big Update · {liked.length} game đã chọn {admin&&'· ADMIN MODE'}</footer>
  {showLogin&&<div className="overlay"><div className="login"><button className="close" onClick={()=>setShowLogin(false)}><X/></button><h2>Đăng ký VietVerse</h2><p>Nhập thông tin để nhận mã xác minh 6 số.</p><input className="field" placeholder="Username" value={username} onChange={e=>setUsername(e.target.value)}/><input className="field" type="email" placeholder="you@gmail.com" value={email} onChange={e=>setEmail(e.target.value)}/><input className="field" type="password" placeholder="Mật khẩu (8+ ký tự)" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<div className="error">{error}</div>}<button className="btn primary full" disabled={busy} onClick={startSignup}>{busy?'Đang gửi...':'Gửi mã OTP'}</button><div className="oauth"><button className="oauthBtn" onClick={()=>flash('Discord OAuth sẽ dùng callback /api/auth/discord/callback khi Client Secret được cấu hình.')}>◉ Discord</button><button className="oauthBtn" onClick={()=>flash('Google OAuth sẽ dùng callback /api/auth/google/callback khi Client ID/Secret được cấu hình.')}>G Google</button></div><p className="muted">API key không nằm trong frontend. Secret chỉ dùng ở server.</p></div></div>}
  {showOtp&&<div className="overlay"><div className="login"><h2>🔐 Xác minh email</h2><p>Mã 6 số đã được gửi tới <b>{email}</b>.</p><input className="field otp" inputMode="numeric" maxLength={6} placeholder="123456" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))}/>{error&&<div className="error">{error}</div>}<button className="btn primary full" disabled={busy} onClick={verify}>{busy?'Đang xác minh...':'Xác minh'}</button><button className="btn full" style={{marginTop:8}} onClick={()=>{setShowOtp(false);setError('')}}>Quay lại</button></div></div>}
 </main>
}