'use client'
import {useEffect,useState} from 'react'
import {Gamepad2,Trophy,UserRound,Users,ShoppingBag,WalletCards,LogOut,X,Sparkles} from 'lucide-react'
const games=[['🌴','Nha Trang Life','Roleplay'],['⚔️','Viet Battle','PvP'],['🌾','Nông Trại Việt','Simulation'],['🏙️','Phố Việt RP','Roleplay']]
type User={id:string;username:string;email:string;coins:number;xp:number;level:number;avatar:string;email_verified:boolean}
export default function Home(){const[user,setUser]=useState<User|null>(null),[show,setShow]=useState(false),[mode,setMode]=useState<'login'|'signup'>('login'),[email,setEmail]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
useEffect(()=>{fetch('/api/auth/me').then(r=>r.json()).then(d=>d.user&&setUser(d.user));const q=new URLSearchParams(location.search);if(q.get('email')==='verified')setNotice('🎉 Email đã được xác minh! Bạn đã đăng nhập.');if(q.get('oauth')==='error')setError('Đăng nhập OAuth thất bại. Hãy kiểm tra cấu hình Google/Discord trong Supabase.')},[])
const submit=async()=>{setError('');setBusy(true);try{const path=mode==='login'?'/api/auth/login':'/api/auth/register';const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,username,password})});const d=await r.json();if(!r.ok)throw Error(d.error);if(mode==='signup'){setNotice('📩 Đã gửi link xác minh tới email. Mở Gmail và bấm “Xác minh email”, không cần mã OTP.');setMode('login')}else{setUser(d.user);setShow(false);setNotice(`👋 Chào mừng ${d.user.username}!`)}}catch(e){setError(e instanceof Error?e.message:'Có lỗi xảy ra.')}finally{setBusy(false)}}
const logout=async()=>{await fetch('/api/auth/logout',{method:'POST'});setUser(null);setShow(false);setNotice('Đã đăng xuất.')}
return <main className="vv"><nav className="nav"><div className="brand">🇻🇳 <span>Viet</span>Verse</div><div className="navlinks"><button className="pill" onClick={()=>location.href='#games'}><Gamepad2 size={16}/> Game</button><button className="pill" onClick={()=>setNotice('🏆 BXH đang đồng bộ dữ liệu thật từ Supabase.') }><Trophy size={16}/> BXH</button><button className="pill" onClick={()=>setNotice('👥 Hệ thống bạn bè đang được đồng bộ.') }><Users size={16}/> Bạn bè</button>{user?<button className="pill" onClick={()=>setShow(true)}><UserRound size={16}/>{user.username}</button>:<button className="pill" onClick={()=>{setMode('login');setShow(true)}}><UserRound size={16}/> Đăng nhập</button>}</div></nav>
<section className="hero"><div><span className="tag"><Sparkles size={13}/> V2 BIG UPDATE</span><h1>Một Việt Nam.<br/><span style={{color:'#2878ff'}}>Một thế giới.</span></h1><p>Game online cộng đồng Việt với avatar, bạn bè, game, chat, XP, Coin và sự kiện.</p><div className="actions"><button className="btn primary" onClick={()=>location.href='#games'}>Chơi ngay</button><button className="btn" onClick={()=>{setMode('signup');setShow(true)}}>Tạo tài khoản</button></div></div><div className="heroCard"><WalletCards size={28}/><h2>VietVerse Online</h2><p>Tài khoản persistent, email verification và đăng nhập Google/Discord.</p><div className="notice">✨ Không còn OTP 6 số — xác minh bằng link email.</div></div></section>
<section className="section" id="games"><h2>🎮 Khám phá game</h2><div className="games">{games.map(([e,n,t])=><button className="game" key={n} onClick={()=>setNotice(`🚀 ${n} đã được chọn.`)}><span className="emoji">{e}</span><strong>{n}</strong><small>Game {t} của VietVerse</small><span className="tag">{t}</span></button>)}</div></section>
<section className="section"><h2>🧩 Hệ thống</h2><div className="games"><div className="game"><UserRound/><strong>Avatar</strong><small>Profile và tùy chỉnh nhân vật.</small></div><div className="game"><ShoppingBag/><strong>Shop</strong><small>Coin, vật phẩm và inventory.</small></div><div className="game"><WalletCards/><strong>Wallet</strong><small>Coins, XP và tiến trình.</small></div><div className="game"><Users/><strong>Friends</strong><small>Bạn bè và party online.</small></div></div></section>
{notice&&<div className="section"><div className="notice">{notice}<button onClick={()=>setNotice('')} style={{float:'right',background:'transparent',border:0,color:'#fff'}}><X size={18}/></button></div></div>}
{user&&<div className="verified">👤 {user.username} · {user.email} · Lv.{user.level} · {user.coins} Coins</div>}
<footer className="footer">VietVerse 🇻🇳 · V2 Big Update</footer>
{show&&<div className="overlay"><div className="login"><button className="close" onClick={()=>setShow(false)}><X/></button>{user?<><h2>👤 {user.username}</h2><p>{user.email}</p><div className="stats"><div className="stat"><small>Coins</small><br/><b>{user.coins}</b></div><div className="stat"><small>Level</small><br/><b>{user.level}</b></div></div><button className="btn full" onClick={logout}><LogOut size={16}/> Đăng xuất</button></>:<><h2>{mode==='login'?'🔐 Đăng nhập':'✨ Tạo tài khoản'}</h2><p>{mode==='login'?'Đăng nhập VietVerse.':'Nhập email thật của bạn. VietVerse sẽ gửi một link xác minh; không cần OTP.'}</p>{mode==='signup'&&<input className="field" placeholder="Username" value={username} onChange={e=>setUsername(e.target.value)}/>}<input className="field" type="email" placeholder="you@gmail.com" value={email} onChange={e=>setEmail(e.target.value)}/><input className="field" type="password" placeholder="Mật khẩu (8+ ký tự)" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<div className="error">{error}</div>}<button className="btn primary full" disabled={busy} onClick={submit}>{busy?'Đang xử lý...':mode==='login'?'Đăng nhập':'Tạo tài khoản'}</button>{mode==='login'&&<div className="oauth"><button className="oauthBtn" onClick={()=>location.href='/api/auth/oauth/discord'}>◉ Đăng nhập Discord</button><button className="oauthBtn" onClick={()=>location.href='/api/auth/oauth/google'}>G Đăng nhập Google</button></div>}<button className="mini" onClick={()=>{setMode(mode==='login'?'signup':'login');setError('')}}>{mode==='login'?'Chưa có tài khoản? Đăng ký':'Đã có tài khoản? Đăng nhập'}</button></>}</div></div>}
</main>}
